server:
  port: 8990
  context-path: /final
  jsp-servlet:
    init-parameters:
      development: true
spring:
  http:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  mvc:
    view:
      prefix: /
      suffix: .jsp
    servlet:
      load-on-startup: 1
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/last
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: com/baizhi/dao/*Dao.xml
  type-aliases-package: com.baizhi.entity