server:
  port: 8990
  context-path: /final
  jsp-servlet:
    init-parameters:
      development: true
spring:
  http:
    encoding:
      charset: utf-8
      force: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/last
mybatis:
  mapper-locations: com/baizhi/dao/*Dao.xml
  type-aliases-package: com.baizhi.entity